version: '3.8'

x-default-environment: &default-environment
  DB_NAME: 'django_forum_v3'
  DB_USER: 'postgres'
  DB_PASSWORD: 'root'
  DB_HOST: 'postgres'
  DB_PORT: '5432'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: 'django_forum_v3'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
    networks:
      - localnet

  celery-broker:
    image: redis
    container_name: celery_broker__redis
    ports:
      - "6379:6379"
    networks:
      - localnet

  celery-worker:
    build:
      context: ./forum_v3
    container_name: celery-worker
    depends_on:
      - celery-broker
      - postgres
    environment:
      <<: *default-environment
    command: >
      sh -c "celery -A forum_v3 worker -l info"
    networks:
      - localnet

  celery-beat:
    build:
      context: ./forum_v3
    container_name: celery_beat
    depends_on:
      - celery-broker
      - postgres
    environment:
      <<: *default-environment
    command: >
      sh -c "celery -A forum_v3 beat -l INFO"
    networks:
      - localnet

  django-forum:
    build:
      context: ./forum_v3
    container_name: core_api
    depends_on:
      - celery-worker
      - celery-beat
      - postgres
    environment:
      <<: *default-environment
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && gunicorn --bind=0.0.0.0:8000 forum_v3.wsgi:application"
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    networks:
      - internet
      - localnet

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - django-forum
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    networks:
      - internet

volumes:
  static_volume:

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
