version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: 'django_forum_v3'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
    networks:
      - localnet

  django-forum:
    build:
      context: ./forum_v3
    container_name: core_api
    depends_on:
      - postgres
    environment:
      DB_NAME: 'django_forum_v3'
      DB_USER: 'postgres'
      DB_PASSWORD: 'root'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
    ports:
      - "8001:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    networks:
      - internet
      - localnet

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
